// Copyright (c) 2026 edwest19
// Generated by Claude.
//
// ============================================================================
// CHANGE NOTE (Claude, Sonnet 5, 2026-08-19):
// This file DIVERGES from SecretLead's version (was a straight port through
// Step 3 of the SecretCsv port — see README.md, chat history). Per an
// explicit request from edwest19:
//
//   - BackupCommand now copies EVERY file in AppData (recursively), not
//     just `.txt`/`.md` pairs — "the whole kit and kaboodle", so a backup
//     is genuinely complete (OneDrive/Dropbox-style), not dependent on a
//     hardcoded extension filter that could silently miss something added
//     to AppData later.
//   - New RestoreCommand does the inverse: copies a previously-backed-up
//     folder's entire contents back into AppData. This intentionally
//     amends README.md §15's original "Backup copies files out, never
//     back in" rule. edwest19's reasoning (paraphrased): that rule existed
//     to stop the app from *interpreting* an arbitrary picked folder's
//     contents as new data (the folder-as-project risk Import already
//     guards against, README.md §3/§13.3) — Restore doesn't interpret
//     anything, it just copies known files back byte-for-byte, so that
//     specific risk doesn't apply. See README.md §14/§15 for the amended
//     rule text.
// ============================================================================

using SecretCsv.Services;
using Windows.Storage.Pickers;

namespace SecretCsv.ViewModels;

/// <summary>
/// Backs the app shell (<see cref="SecretCsv.MainPage"/>): the persistent
/// left nav rail (Import, Browse, Status, Exit in the main action group;
/// Backup, Restore pinned at the bottom as infrequent/administrative
/// actions — README.md §14) plus the content frame that hosts every other
/// screen (browse/list, Import, etc.).
/// </summary>
public sealed class MainPageViewModel : ObservableObject
{
    // Import navigates ContentFrame directly, so it's a Click handler in
    // MainPage.xaml.cs rather than a command here — no ViewModel-side
    // command needed for it.
    public RelayCommand BackupCommand { get; }
    public RelayCommand RestoreCommand { get; }
    public RelayCommand ExitCommand { get; }

    /// <summary>Shared status/validation messages shown in the Status flyout (README.md §3).</summary>
    public StatusService Status => App.Status;

    private readonly EntityStore _entityStore = new();

    public MainPageViewModel()
    {
        BackupCommand = new RelayCommand(async () => await BackupAsync());
        RestoreCommand = new RelayCommand(async () => await RestoreAsync());
        ExitCommand = new RelayCommand(Exit);
    }

    /// <summary>
    /// Prompts for a destination folder, then copies AppData's entire
    /// contents into it, recursively (README.md §14) — a safety net
    /// against the AppData-wipe scenario SecretList hit (its
    /// <c>records.txt</c> was lost with no recoverable trace after a
    /// Windows feature update), and the "out" half of a full backup/
    /// restore cycle around an uninstall.
    /// </summary>
    private async Task BackupAsync()
    {
        if (!Directory.Exists(_entityStore.RootFolder) ||
            Directory.GetFiles(_entityStore.RootFolder, "*", SearchOption.AllDirectories).Length == 0)
        {
            App.Status.SetMessages(["Nothing to back up yet."]);
            return;
        }

        var picker = new FolderPicker();
        WinRT.Interop.InitializeWithWindow.Initialize(picker, App.WindowHandle);
        picker.FileTypeFilter.Add("*");
        picker.SuggestedStartLocation = PickerLocationId.Desktop;

        var folder = await picker.PickSingleFolderAsync();
        if (folder is null)
        {
            return;
        }

        var copiedCount = CopyDirectoryRecursive(_entityStore.RootFolder, folder.Path);
        App.Status.SetMessages([$"Backed up {copiedCount} file(s) to {folder.Path}."]);
    }

    /// <summary>
    /// Prompts for a folder to restore from, then copies its entire
    /// contents into AppData, recursively, overwriting on conflict — the
    /// "in" half of the backup/restore cycle: back up, uninstall,
    /// reinstall, restore. Copies whatever is in the picked folder
    /// wholesale, trusting it rather than parsing/validating it — unlike
    /// Import (README.md §3, §9), this isn't interpreting arbitrary data,
    /// just restoring the app's own previously-exported files, so the
    /// folder-as-project risk that rule exists for doesn't apply here
    /// (README.md §15).
    /// </summary>
    private async Task RestoreAsync()
    {
        var picker = new FolderPicker();
        WinRT.Interop.InitializeWithWindow.Initialize(picker, App.WindowHandle);
        picker.FileTypeFilter.Add("*");
        picker.SuggestedStartLocation = PickerLocationId.Desktop;

        var folder = await picker.PickSingleFolderAsync();
        if (folder is null)
        {
            return;
        }

        var sourceFileCount = Directory.GetFiles(folder.Path, "*", SearchOption.AllDirectories).Length;
        if (sourceFileCount == 0)
        {
            App.Status.SetMessages(["Nothing to restore — that folder is empty."]);
            return;
        }

        var copiedCount = CopyDirectoryRecursive(folder.Path, _entityStore.RootFolder);
        App.Status.SetMessages([$"Restored {copiedCount} file(s) from {folder.Path}. Switch to Browse to see them."]);
    }

    /// <summary>
    /// Recursively copies every file under <paramref name="sourceDir"/>
    /// into <paramref name="destDir"/>, preserving relative subfolder
    /// structure and overwriting on conflict. Never deletes anything at
    /// the destination that isn't also in the source — additive only,
    /// same philosophy as records never being deleted by Import (README.md
    /// §6). Returns the number of files copied.
    /// </summary>
    private static int CopyDirectoryRecursive(string sourceDir, string destDir)
    {
        Directory.CreateDirectory(destDir);

        var files = Directory.GetFiles(sourceDir, "*", SearchOption.AllDirectories);
        foreach (var filePath in files)
        {
            var relativePath = Path.GetRelativePath(sourceDir, filePath);
            var destPath = Path.Combine(destDir, relativePath);
            var destFileDir = Path.GetDirectoryName(destPath);
            if (destFileDir is not null)
            {
                Directory.CreateDirectory(destFileDir);
            }

            File.Copy(filePath, destPath, overwrite: true);
        }

        return files.Length;
    }

    private void Exit()
    {
        App.Window.Close();
    }
}
