// Copyright (c) 2026 edwest19
// Generated by Claude.
//
// ============================================================================
// PORT NOTE (Claude, Sonnet 5, 2026-08-18):
// Adapted from SecretLead's App.xaml.cs as part of the SecretLead ->
// SecretCsv port (Step 3 - see README.md, chat history). This REPLACES
// SecretCsv's original template App.xaml.cs (a private `_window` field,
// no statics, no crash logging) with SecretLead's version, namespace-
// adjusted. This is necessary, not cosmetic: every ViewModel in this port
// (MainPageViewModel, ImportPageViewModel, BrowsePageViewModel) reads
// App.Window / App.WindowHandle / App.DispatcherQueue / App.Status, none
// of which existed on SecretCsv's template App class.
//
// Behavior otherwise identical to SecretLead's version: crash logging via
// AppDomain.UnhandledException + Application.UnhandledException, writing a
// best-effort SecretCsv-crash.txt to the Desktop (renamed from
// SecretLead-crash.txt — everything else about LogCrash is unchanged).
// ============================================================================

using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Data;
using Microsoft.UI.Xaml.Input;
using Microsoft.UI.Xaml.Media;
using Microsoft.UI.Xaml.Navigation;
using SecretCsv.ViewModels;

// To learn more about WinUI, the WinUI project structure,
// and more about our project templates, see: http://aka.ms/winui-project-info.

namespace SecretCsv;

/// <summary>
/// Provides application-specific behavior to supplement the default Application class.
/// </summary>
public partial class App : Application
{
    /// <summary>
    /// The main application window. Use <c>App.Window</c> from any class that needs
    /// the window reference (for dialogs, pickers, interop, etc.).
    /// </summary>
    public static Window Window { get; private set; } = null!;

    /// <summary>
    /// The UI thread dispatcher. Use <c>App.DispatcherQueue</c> to marshal calls
    /// to the UI thread. Fully qualified to avoid CS0104 ambiguity with
    /// <see cref="Windows.System.DispatcherQueue"/>.
    /// </summary>
    public static Microsoft.UI.Dispatching.DispatcherQueue DispatcherQueue { get; private set; } = null!;

    /// <summary>
    /// The native window handle (HWND). Use for file pickers,
    /// <c>DataTransferManager</c>, and any WinRT interop that requires
    /// <c>InitializeWithWindow</c>.
    /// </summary>
    public static nint WindowHandle =>
        WinRT.Interop.WindowNative.GetWindowHandle(Window);

    /// <summary>
    /// Shared status/validation messages shown in the nav rail's Status
    /// flyout (README.md §3). Use <c>App.Status</c> from any page that
    /// needs to report validation results or errors.
    /// </summary>
    public static StatusService Status { get; } = new();

    /// <summary>
    /// Initializes the singleton application object.
    /// </summary>
    public App()
    {
        AppDomain.CurrentDomain.UnhandledException += (_, e) =>
            LogCrash(e.ExceptionObject as Exception ?? new Exception($"Non-exception object thrown: {e.ExceptionObject}"));

        try
        {
            InitializeComponent();
        }
        catch (Exception ex)
        {
            LogCrash(ex);
            throw;
        }
    }

    /// <summary>
    /// Invoked when the application is launched.
    /// </summary>
    /// <param name="args">Details about the launch request and process.</param>
    protected override void OnLaunched(Microsoft.UI.Xaml.LaunchActivatedEventArgs args)
    {
        this.UnhandledException += (_, e) => LogCrash(e.Exception);

        try
        {
            Window = new MainWindow();
            DispatcherQueue = Microsoft.UI.Dispatching.DispatcherQueue.GetForCurrentThread();
            Window.Activate();
        }
        catch (Exception ex)
        {
            LogCrash(ex);
            throw;
        }
    }

    private static void LogCrash(Exception ex)
    {
        try
        {
            var path = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Desktop), "SecretCsv-crash.txt");
            File.WriteAllText(path, ex.ToString());
        }
        catch { /* best-effort */ }
    }
}
