// Copyright (c) 2026 edwest19
// Generated by Claude.
//
// ============================================================================
// PORT NOTE (Claude, Sonnet 5, 2026-08-18):
// Ported from SecretLead's ImportPage.xaml.cs as part of the SecretLead ->
// SecretCsv port (Step 4 - see README.md, chat history). New file in
// SecretCsv (see MainPage's port note for why). Namespace adjusted
// (SecretLead -> SecretCsv.Views), plus an explicit
// `using SecretCsv.ViewModels;` that SecretLead's version didn't need,
// since Views and ViewModels are sibling namespaces here, not
// ancestor/descendant. Logic otherwise unchanged from SecretLead's
// working, reviewed version.
// ============================================================================

using Microsoft.UI.Xaml.Controls;
using SecretCsv.ViewModels;

namespace SecretCsv.Views;

/// <summary>The Import screen (README.md §3).</summary>
public sealed partial class ImportPage : Page
{
    public ImportPageViewModel ViewModel { get; } = new();

    public ImportPage()
    {
        InitializeComponent();
    }
}
