// Copyright (c) 2026 edwest19.
// Generated by Claude (Sonnet 5), 2026-08-02: moved from project root into
// Views/ as part of establishing SecretCsv's folder structure (App/MainWindow
// stay at root as the composition root; all pages live under Views/).
using Microsoft.UI.Xaml.Controls;

// To learn more about WinUI, the WinUI project structure,
// and more about our project templates, see: http://aka.ms/winui-project-info.

namespace SecretCsv.Views;

/// <summary>
/// The main content page displayed inside the application window.
/// Add your UI logic, event handlers, and data binding here.
/// </summary>
public sealed partial class MainPage : Page
{
    public MainPage()
    {
        InitializeComponent();

        // TODO: Add your initialization logic here.
    }
}
