// Copyright (c) 2026 edwest19
// Generated by Claude.
//
// ============================================================================
// PORT NOTE (Claude, Sonnet 5, 2026-08-18):
// Adapted from SecretLead's MainPage.xaml.cs as part of the SecretLead ->
// SecretCsv port (Step 4 - see README.md, chat history). This REPLACES
// SecretCsv's original blank scaffold Views\MainPage.xaml.cs. Namespace
// adjusted for SecretCsv's Views\ convention (SecretLead -> SecretCsv.
// Views), plus an explicit `using SecretCsv.ViewModels;` that SecretLead's
// version didn't need — SecretLead kept everything in one flat namespace,
// but SecretCsv.Views and SecretCsv.ViewModels are sibling namespaces, not
// ancestor/descendant, so MainPageViewModel isn't visible here without it.
// Logic otherwise unchanged from SecretLead's working, reviewed version.
// ============================================================================

using Microsoft.UI.Xaml.Controls;
using SecretCsv.ViewModels;

// To learn more about WinUI, the WinUI project structure,
// and more about our project templates, see: http://aka.ms/winui-project-info.

namespace SecretCsv.Views;

/// <summary>
/// The main content page displayed inside the application window.
/// </summary>
public sealed partial class MainPage : Page
{
    public MainPageViewModel ViewModel { get; } = new();

    public MainPage()
    {
        InitializeComponent();

        // BrowsePage is the app's home content (README.md §6, §7) — shown
        // by default rather than an empty content frame.
        ContentFrame.Navigate(typeof(BrowsePage));
    }

    // Frame navigation is a view concern, so these stay in code-behind
    // rather than routed through a ViewModel command.
    private void ImportButton_Click(object sender, Microsoft.UI.Xaml.RoutedEventArgs e)
    {
        ContentFrame.Navigate(typeof(ImportPage));
    }

    private void BrowseButton_Click(object sender, Microsoft.UI.Xaml.RoutedEventArgs e)
    {
        ContentFrame.Navigate(typeof(BrowsePage));
    }
}
