// Copyright (c) 2026 edwest19
// Generated by Claude.
//
// ============================================================================
// PORT NOTE (Claude, Sonnet 5, 2026-08-18):
// Ported verbatim from SecretLead's Services\ConstructionFixups.cs as part
// of the SecretLead -> SecretCsv port (Step 2a - see README.md, chat
// history). Only the namespace/using changed (SecretLead.* -> SecretCsv.*);
// the logic below is byte-for-byte identical to SecretLead's working,
// reviewed version. This is the Construction-only exception referenced in
// README.md §8 — deliberately NOT a generalized rule other tag files
// inherit; gated on entity name == "Construction" exactly.
// ============================================================================

using SecretCsv.Models;

namespace SecretCsv.Services;

/// <summary>
/// The one field-normalization rule that is NOT generalized to every tag
/// file (README.md §8): when the sample Construction tag file's
/// "Business Name" is blank, fall back to "Last Name, First Name". Gated on
/// the entity actually being named "Construction" — not just on having
/// those three tag names — so an unrelated user-authored tag file that
/// happens to reuse those tag names isn't silently affected.
/// </summary>
public static class ConstructionFixups
{
    private const string ConstructionEntityName = "Construction";
    private const string BusinessNameTag = "Business Name";
    private const string LastNameTag = "Last Name";
    private const string FirstNameTag = "First Name";

    public static void Apply(TagFileDefinition tagFile, IDictionary<string, string> normalizedValues)
    {
        if (!string.Equals(tagFile.EntityName, ConstructionEntityName, StringComparison.Ordinal))
        {
            return;
        }

        if (!HasTag(tagFile, BusinessNameTag) || !HasTag(tagFile, LastNameTag) || !HasTag(tagFile, FirstNameTag))
        {
            return;
        }

        if (!string.IsNullOrWhiteSpace(normalizedValues[BusinessNameTag]))
        {
            return;
        }

        normalizedValues[BusinessNameTag] = $"{normalizedValues[LastNameTag]}, {normalizedValues[FirstNameTag]}";
    }

    private static bool HasTag(TagFileDefinition tagFile, string tagName) =>
        tagFile.Tags.Any(t => string.Equals(t, tagName, StringComparison.OrdinalIgnoreCase));
}
