// Copyright (c) 2026 edwest19
// Generated by Claude.
//
// ============================================================================
// PORT NOTE (Claude, Sonnet 5, 2026-08-18):
// Ported verbatim from SecretLead's Services\CsvParser.cs as part of the
// SecretLead -> SecretCsv port (Step 2a - see README.md, chat history).
// Only the namespace/using changed (SecretLead.* -> SecretCsv.*); the logic
// below is byte-for-byte identical to SecretLead's working, reviewed
// version. Pure string parsing, no file I/O of its own — the caller reads
// the CSV file's text and passes it in.
// ============================================================================

using System.Text;
using SecretCsv.Models;

namespace SecretCsv.Services;

/// <summary>
/// A small hand-rolled CSV reader (RFC 4180-ish: quoted fields, embedded
/// commas/newlines, <c>""</c> as an escaped quote) — no third-party CSV
/// library, per README.md §2/§15.
/// </summary>
public static class CsvParser
{
    public static CsvTable Parse(string csvText)
    {
        var rows = ParseRows(csvText);

        if (rows.Count == 0)
        {
            throw new CsvFormatException("CSV file is empty.");
        }

        var headers = rows[0];
        if (headers.Count == 0 || headers.All(h => h.Length == 0))
        {
            throw new CsvFormatException("CSV file has no header row.");
        }

        var dataRows = new List<IReadOnlyDictionary<string, string>>();

        for (var r = 1; r < rows.Count; r++)
        {
            var rawRow = rows[r];

            // Skip a fully-blank trailing row (common at the end of
            // exported CSVs) rather than importing a garbage record.
            if (rawRow.Count == 1 && rawRow[0].Length == 0)
            {
                continue;
            }

            var rowValues = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            for (var c = 0; c < headers.Count; c++)
            {
                rowValues[headers[c]] = c < rawRow.Count ? rawRow[c] : string.Empty;
            }

            dataRows.Add(rowValues);
        }

        return new CsvTable
        {
            Headers = headers,
            Rows = dataRows,
        };
    }

    private static List<List<string>> ParseRows(string text)
    {
        var rows = new List<List<string>>();
        var currentRow = new List<string>();
        var field = new StringBuilder();
        var inQuotes = false;
        var sawAnyContentOnRow = false;
        var i = 0;
        var length = text.Length;

        void FinishField()
        {
            currentRow.Add(field.ToString());
            field.Clear();
        }

        void FinishRow()
        {
            FinishField();
            rows.Add(currentRow);
            currentRow = [];
            sawAnyContentOnRow = false;
        }

        while (i < length)
        {
            var c = text[i];

            if (inQuotes)
            {
                if (c == '"')
                {
                    if (i + 1 < length && text[i + 1] == '"')
                    {
                        field.Append('"');
                        i += 2;
                    }
                    else
                    {
                        inQuotes = false;
                        i++;
                    }
                }
                else
                {
                    field.Append(c);
                    i++;
                }

                continue;
            }

            switch (c)
            {
                case '"':
                    inQuotes = true;
                    sawAnyContentOnRow = true;
                    i++;
                    break;

                case ',':
                    FinishField();
                    sawAnyContentOnRow = true;
                    i++;
                    break;

                case '\r':
                    FinishRow();
                    i++;
                    if (i < length && text[i] == '\n')
                    {
                        i++;
                    }

                    break;

                case '\n':
                    FinishRow();
                    i++;
                    break;

                default:
                    field.Append(c);
                    sawAnyContentOnRow = true;
                    i++;
                    break;
            }
        }

        if (field.Length > 0 || currentRow.Count > 0 || sawAnyContentOnRow)
        {
            FinishRow();
        }

        return rows;
    }
}
