// Copyright (c) 2026 edwest19
// Generated by Claude.
//
// ============================================================================
// PORT NOTE (Claude, Sonnet 5, 2026-08-18):
// Adapted from SecretLead's Services\EntityStore.cs as part of the
// SecretLead -> SecretCsv port (Step 2b - see README.md §5, §14, §16, and
// chat history). This is NOT a byte-for-byte port like Steps 1/2a — the
// AppData folder-resolution logic was deliberately changed, per an explicit
// decision from edwest19:
//
//   SecretCsv uses real packaged storage
//   (Windows.Storage.ApplicationData.Current.LocalFolder), not the plain
//   hardcoded %LOCALAPPDATA%\SecretCsv\ folder SecretLead used. SecretLead
//   couldn't use packaged storage — it ships unpackaged/self-contained, and
//   ApplicationData.Current throws without package identity. SecretCsv IS
//   packaged and signed, so that constraint doesn't apply here.
//
//   Reasoning (edwest19, paraphrased): uninstalling SecretCsv should leave
//   nothing behind — no leftover folder, no garbage on disk. Importing into
//   a clean, package-scoped AppData store means fewer weird failure modes,
//   and it's how a "real," professional Windows app is expected to behave.
//   This is also why the Backup button (README.md §14) exists — export the
//   folder before uninstalling if you want to keep it.
//
// Everything else in this class (path-building, existence checks, read/
// write logic) is unchanged from SecretLead's version — it all just
// operates on a plain folder-path string once it has one, so none of it
// needed to change.
//
// CAVEAT — not yet verified against a real run:
// ApplicationData.Current requires package identity at runtime. That's
// satisfied when SecretCsv is (a) installed and launched as the signed
// MSIX, or (b) launched via `dotnet run`, which
// Microsoft.Windows.SDK.BuildTools.WinApp (already referenced in
// SecretCsv.csproj) gives package identity to via a registered debug AUMID.
// It is NOT satisfied by double-clicking the raw .exe under bin\Debug\...\
// directly — that will throw. `dotnet build` alone won't exercise this at
// all, since nothing calls `new EntityStore()` yet (that's Step 3,
// ViewModels) — this needs a real run to confirm, not just a clean build.
// ============================================================================

using SecretCsv.Models;
using Windows.Storage;

namespace SecretCsv.Services;

/// <summary>
/// Reads and writes the app's sandboxed AppData storage — the only place
/// SecretCsv ever writes (README.md §5). Each entity is a pair of files,
/// keyed only by entity name, with no per-source or per-import-session
/// isolation:
/// <list type="bullet">
/// <item><c>&lt;EntityName&gt;.md</c> — the reference copy of the tag file that produced this entity.</item>
/// <item><c>&lt;EntityName&gt;.txt</c> — the actual records.</item>
/// </list>
/// Existence of <c>&lt;EntityName&gt;.txt</c> is the entire discovery
/// mechanism (README.md §6) — there is no separate index or manifest.
/// </summary>
public sealed class EntityStore
{
    private readonly string _rootFolder;

    /// <summary>The AppData folder entities are read from and written to.</summary>
    public string RootFolder => _rootFolder;

    /// <summary>
    /// Uses the app's real packaged AppData local folder
    /// (<c>Windows.Storage.ApplicationData.Current.LocalFolder</c>), so
    /// everything SecretCsv writes is genuinely tied to package identity
    /// and gets removed automatically on uninstall — no leftover folder,
    /// no manual cleanup (README.md §14). Requires package identity at
    /// runtime — see the PORT NOTE above for exactly when that is and
    /// isn't true, and note this hasn't been confirmed against a real run
    /// of SecretCsv yet.
    /// </summary>
    public EntityStore()
        : this(ApplicationData.Current.LocalFolder.Path)
    {
    }

    /// <summary>Points at an arbitrary folder — for tests or diagnostics only.</summary>
    internal EntityStore(string rootFolder)
    {
        _rootFolder = rootFolder;
    }

    private string TagFilePath(string entityName) => Path.Combine(_rootFolder, $"{entityName}.md");

    private string RecordsFilePath(string entityName) => Path.Combine(_rootFolder, $"{entityName}.txt");

    /// <summary>
    /// True if this entity has ever been imported/seeded — i.e. its
    /// records file exists. This, not any config or index, is the
    /// existence-of-file mechanic from README.md §6.
    /// </summary>
    public bool EntityExists(string entityName) => File.Exists(RecordsFilePath(entityName));

    /// <summary>
    /// Every entity currently in AppData, discovered by the
    /// <c>&lt;EntityName&gt;.txt</c> files present — not by any folder the
    /// owner has open (README.md §6).
    /// </summary>
    public IReadOnlyList<string> ListEntityNames()
    {
        if (!Directory.Exists(_rootFolder))
        {
            return [];
        }

        return Directory.GetFiles(_rootFolder, "*.txt")
            .Select(Path.GetFileNameWithoutExtension)
            .Where(name => !string.IsNullOrEmpty(name))
            .Select(name => name!)
            .OrderBy(name => name, StringComparer.OrdinalIgnoreCase)
            .ToList();
    }

    /// <summary>Reads and parses an entity's stored tag-file copy.</summary>
    /// <exception cref="FileNotFoundException">No tag file is stored for this entity.</exception>
    /// <exception cref="TagFileFormatException">The stored tag file is malformed.</exception>
    public TagFileDefinition GetTagFile(string entityName)
    {
        var path = TagFilePath(entityName);
        if (!File.Exists(path))
        {
            throw new FileNotFoundException($"No stored tag file for entity '{entityName}'.", path);
        }

        return TagFileParser.Parse(File.ReadAllText(path));
    }

    /// <summary>
    /// Writes (or overwrites) an entity's tag-file copy. Called at Import
    /// time (README.md §3 step 2) before records are written, so the store
    /// always has its own self-describing copy independent of wherever the
    /// original tag file came from.
    /// </summary>
    public void SaveTagFile(string entityName, string tagFileMarkdownText)
    {
        Directory.CreateDirectory(_rootFolder);
        File.WriteAllText(TagFilePath(entityName), tagFileMarkdownText);
    }

    /// <summary>
    /// Reads and parses an entity's stored records. Returns an empty list
    /// (not an error) if the entity doesn't exist yet.
    /// </summary>
    public IReadOnlyList<EntityRecord> GetRecords(string entityName)
    {
        var path = RecordsFilePath(entityName);
        if (!File.Exists(path))
        {
            return [];
        }

        return EntityRecordSerializer.Parse(File.ReadAllText(path));
    }

    /// <summary>
    /// Appends records to an entity's store without touching anything
    /// already there — records are never deleted or overwritten by this
    /// call (README.md §3 step 4, §6). Requires the entity's tag file to
    /// already be saved (via <see cref="SaveTagFile"/>), since that's what
    /// supplies field order for the new lines — matching the ordering in
    /// README.md §3, where the tag file is copied in before records are
    /// written.
    /// </summary>
    /// <exception cref="FileNotFoundException">No tag file is stored for this entity yet.</exception>
    public void AppendRecords(string entityName, IEnumerable<EntityRecord> newRecords)
    {
        var recordsList = newRecords as ICollection<EntityRecord> ?? newRecords.ToList();
        if (recordsList.Count == 0)
        {
            return;
        }

        var tagFile = GetTagFile(entityName);
        var newText = EntityRecordSerializer.Serialize(recordsList, tagFile.Tags);

        Directory.CreateDirectory(_rootFolder);
        var path = RecordsFilePath(entityName);

        if (!File.Exists(path))
        {
            File.WriteAllText(path, newText);
            return;
        }

        var existingText = File.ReadAllText(path).TrimEnd('\n', '\r');
        File.WriteAllText(path, existingText + "\n\n" + newText);
    }

    /// <summary>
    /// Overwrites an entity's entire record store. Used by manual
    /// edit/delete flows (README.md §7) — Import never calls this, it only
    /// ever appends.
    /// </summary>
    /// <exception cref="FileNotFoundException">No tag file is stored for this entity yet.</exception>
    public void SaveRecords(string entityName, IEnumerable<EntityRecord> records)
    {
        var tagFile = GetTagFile(entityName);
        Directory.CreateDirectory(_rootFolder);
        File.WriteAllText(RecordsFilePath(entityName), EntityRecordSerializer.Serialize(records, tagFile.Tags));
    }
}
