// Copyright (c) 2026 edwest19
// Generated by Claude.
//
// ============================================================================
// PORT NOTE (Claude, Sonnet 5, 2026-08-18):
// Ported verbatim from SecretLead's Services\FieldNormalizer.cs as part of
// the SecretLead -> SecretCsv port (Step 2a - see README.md, chat history).
// No namespace-qualified type references in this file, so only the
// namespace declaration itself changed (SecretLead.Services ->
// SecretCsv.Services); the logic below is byte-for-byte identical to
// SecretLead's working, reviewed version.
// ============================================================================

using System.Globalization;

namespace SecretCsv.Services;

/// <summary>
/// Field normalization inferred purely from tag-name substring, no
/// separate datatype field (README.md §8):
/// <list type="bullet">
/// <item>"date" → reformatted to mm/dd/yyyy regardless of source format.</item>
/// <item>"phone" → stripped to digits, reformatted by digit count.</item>
/// <item>"email" (and everything else) → stored as-is.</item>
/// </list>
/// </summary>
public static class FieldNormalizer
{
    public static string Normalize(string tagName, string rawValue)
    {
        if (tagName.Contains("date", StringComparison.OrdinalIgnoreCase))
        {
            return NormalizeDate(rawValue);
        }

        if (tagName.Contains("phone", StringComparison.OrdinalIgnoreCase))
        {
            return NormalizePhone(rawValue);
        }

        return rawValue;
    }

    private static string NormalizeDate(string rawValue)
    {
        if (string.IsNullOrWhiteSpace(rawValue))
        {
            return rawValue;
        }

        // Invariant culture reads ambiguous m/d/y-style dates as US-style
        // month/day/year, matching the Suffolk County exports this was
        // built against. Anything unparseable is left as-is rather than
        // dropped — a human reviews imported records before trusting them
        // (README.md §15).
        return DateTime.TryParse(rawValue, CultureInfo.InvariantCulture, DateTimeStyles.None, out var parsed)
            ? parsed.ToString("MM/dd/yyyy", CultureInfo.InvariantCulture)
            : rawValue;
    }

    private static string NormalizePhone(string rawValue)
    {
        var digits = new string(rawValue.Where(char.IsDigit).ToArray());

        return digits.Length switch
        {
            10 => $"({digits[..3]}) {digits[3..6]}-{digits[6..]}",
            11 => $"+1 ({digits[1..4]}) {digits[4..7]}-{digits[7..]}",
            7 => $"{digits[..3]}-{digits[3..]}",
            _ => rawValue,
        };
    }
}
