// Copyright (c) 2026 edwest19
// Generated by Claude.
//
// ============================================================================
// PORT NOTE (Claude, Sonnet 5, 2026-08-18):
// Ported verbatim from SecretLead's Services\RecordPrintFormatter.cs as
// part of the SecretLead -> SecretCsv port (Step 2a - see README.md, chat
// history). Only the namespace/using changed (SecretLead.* -> SecretCsv.*);
// the logic below is byte-for-byte identical to SecretLead's working,
// reviewed version. Pure string formatting, no file I/O.
// ============================================================================

using SecretCsv.Models;

namespace SecretCsv.Services;

/// <summary>
/// Renders records as human-readable Markdown — the entity name as a
/// heading, then one "TagName: Value" line per tag, each separated by a
/// blank line so every field renders as its own paragraph rather than
/// Markdown collapsing them into one run-on line. For Construction (12
/// tags) that's 1 + 12 = 13 lines per record. This is what the Export
/// button writes to a .md file, deliberately not the raw
/// <c>:tag.TagName.Value</c> storage format (README.md §5) — the point is
/// to be readable without knowing SecretCsv's internals.
/// </summary>
public static class RecordPrintFormatter
{
    public static string FormatRecord(TagFileDefinition tagFile, EntityRecord record)
    {
        var lines = new List<string> { $"## {tagFile.EntityName}" };

        foreach (var tag in tagFile.Tags)
        {
            lines.Add($"{tag}: {record.GetValue(tag) ?? string.Empty}");
        }

        return string.Join("\n\n", lines) + "\n";
    }

    /// <summary>Every record, blank-line separated.</summary>
    public static string FormatRecords(TagFileDefinition tagFile, IEnumerable<EntityRecord> records) =>
        string.Join("\n", records.Select(r => FormatRecord(tagFile, r)));
}
