// Copyright (c) 2026 edwest19
// Generated by Claude.
//
// ============================================================================
// PORT NOTE (Claude, Sonnet 5, 2026-08-18):
// Ported verbatim from SecretLead's Services\TagFileParser.cs as part of the
// SecretLead -> SecretCsv port (Step 2a - see README.md, chat history).
// Only the namespace/using changed (SecretLead.* -> SecretCsv.*); the logic
// below is byte-for-byte identical to SecretLead's working, reviewed
// version. This file operates purely on an already-read string (the
// AppData path/file-read happens in EntityStore, which is Step 2b, not yet
// ported pending the AppData folder-resolution decision in README.md §14).
// ============================================================================

using SecretCsv.Models;

namespace SecretCsv.Services;

/// <summary>
/// Parses a tag file's Markdown text into a <see cref="TagFileDefinition"/>,
/// per the grammar in README.md §4:
/// <list type="bullet">
/// <item><c>#</c> — title/description/version/date; informational only, parsed past.</item>
/// <item><c>##</c> — entity name (exactly one required).</item>
/// <item><c>### TAG X</c> — a tag name (at least 2 required).</item>
/// </list>
/// This is a name-matcher and two positional roles, not a schema in the
/// type/constraint sense — see README.md §13.2 ("never use the word
/// 'schema'").
/// </summary>
public static class TagFileParser
{
    private const string TagLinePrefix = "### TAG ";
    private const string EntityLinePrefix = "## ";

    /// <exception cref="TagFileFormatException">
    /// The text doesn't have exactly one <c>##</c> line, or has fewer than
    /// 2 <c>### TAG</c> lines.
    /// </exception>
    public static TagFileDefinition Parse(string markdown)
    {
        string? entityName = null;
        var tags = new List<string>();

        foreach (var rawLine in markdown.Replace("\r\n", "\n").Split('\n'))
        {
            var line = rawLine.TrimEnd();

            if (line.StartsWith(TagLinePrefix, StringComparison.Ordinal))
            {
                var tagName = line[TagLinePrefix.Length..].Trim();
                if (tagName.Length == 0)
                {
                    throw new TagFileFormatException("Found a '### TAG' line with no tag name after it.");
                }

                tags.Add(tagName);
            }
            else if (line.StartsWith(EntityLinePrefix, StringComparison.Ordinal))
            {
                // "### TAG X" never matches this branch: its 3rd character
                // is '#', not a space, so it fails the "## " prefix check
                // before we even get here.
                var name = line[EntityLinePrefix.Length..].Trim();

                if (entityName is not null)
                {
                    throw new TagFileFormatException(
                        $"Found more than one '##' entity-name line ('{entityName}' and '{name}'). " +
                        "A tag file must declare exactly one entity name.");
                }

                if (name.Length == 0)
                {
                    throw new TagFileFormatException("Found a '##' line with no entity name after it.");
                }

                entityName = name;
            }
        }

        if (entityName is null)
        {
            throw new TagFileFormatException(
                "No '## EntityName' line found — a tag file must declare exactly one entity name.");
        }

        if (tags.Count < 2)
        {
            throw new TagFileFormatException(
                $"Tag file for '{entityName}' declares only {tags.Count} tag(s). At least 2 are required: " +
                "the first plays the Category role, the second the Nickname role (README.md §4).");
        }

        return new TagFileDefinition
        {
            EntityName = entityName,
            Tags = tags,
        };
    }
}
