// Copyright (c) 2026 edwest19
// Generated by Claude.
//
// ============================================================================
// PORT NOTE (Claude, Sonnet 5, 2026-08-18):
// Ported verbatim from SecretLead's Services\TagFileFormatException.cs as
// part of the SecretLead -> SecretCsv port (Step 2a - see README.md, chat
// history). Only the namespace declaration changed (SecretLead.Services ->
// SecretCsv.Services); otherwise identical.
// ============================================================================

namespace SecretCsv.Services;

/// <summary>
/// Thrown when a tag file's Markdown doesn't follow the grammar in
/// README.md §4 — for example no <c>##</c> entity-name line, more than one
/// of them, or fewer than the 2 tags required for the Category/Nickname
/// roles.
/// </summary>
public sealed class TagFileFormatException : Exception
{
    public TagFileFormatException(string message) : base(message)
    {
    }
}
