# Copyright (c) 2026 edwest19
# Generated by Claude.
#
# ============================================================================
# NOTE (Claude, Sonnet 5, 2026-08-19):
# Adapted from SecretLead's scripts\Reset-SecretLeadAppData.ps1 -- but NOT a
# straight port, unlike most of this repo's ported code (see README.md,
# chat history). SecretLead's version targets a plain, hardcoded
# %LOCALAPPDATA%\SecretLead\ folder, which was correct for SecretLead's
# unpackaged distribution model. SecretCsv is a packaged, signed MSIX whose
# EntityStore deliberately uses real packaged AppData storage
# (Windows.Storage.ApplicationData.Current.LocalFolder -- README.md section
# 5, 14, 16), which lives at a path that depends on the installed package's
# family name, not a name you can hardcode. This script finds that path
# dynamically instead of guessing at it.
# ============================================================================

<#
.SYNOPSIS
    Resets SecretCsv to first-run state.

.DESCRIPTION
    Deletes every stored entity (<EntityName>.md / <EntityName>.txt) from
    SecretCsv's AppData folder. Existence-of-file is the whole mechanism
    SecretCsv uses to know what entities exist (README.md section 6), so
    removing these files is a complete, clean reset -- there's no other
    index, cache, or database tracking anything.

    SecretCsv's EntityStore uses real packaged AppData storage
    (Windows.Storage.ApplicationData.Current.LocalFolder), which resolves
    to:

        %LOCALAPPDATA%\Packages\<PackageFamilyName>\LocalState

    <PackageFamilyName> is derived from the package's Identity Name and
    Publisher and can change across builds/signing, so this script never
    hardcodes it. Instead it reads the Identity Name straight out of
    Package.appxmanifest (next to this script's parent folder) and asks
    Windows for the matching installed package via Get-AppxPackage. This
    works whether SecretCsv is running as the installed, signed MSIX, or
    via `dotnet run`'s debug-registered package identity
    (Microsoft.Windows.SDK.BuildTools.WinApp registers under the same
    Identity Name either way).

    Note this is deliberately narrower than the Backup button (README.md
    section 14): Backup copies EVERYTHING in AppData, recursively, for a
    genuine full backup. This script only removes the `.md`/`.txt` entity
    pairs that existence-of-file actually keys on, since that's precisely
    what "first-run state" means for SecretCsv -- not a blanket wipe of
    whatever else might ever end up in that folder.

.PARAMETER Force
    Skip the confirmation prompt.

.EXAMPLE
    .\scripts\Reset-SecretCsvAppData.ps1

.EXAMPLE
    .\scripts\Reset-SecretCsvAppData.ps1 -Force

.NOTES
    If Windows blocks this script ("running scripts is disabled on this
    system"), either right-click the file > Properties > Unblock, or run:
        powershell -ExecutionPolicy Bypass -File .\scripts\Reset-SecretCsvAppData.ps1
#>
[CmdletBinding(SupportsShouldProcess, ConfirmImpact = 'High')]
param(
    [switch]$Force
)

$manifestPath = Join-Path $PSScriptRoot "..\Package.appxmanifest"
if (-not (Test-Path $manifestPath)) {
    Write-Error "Could not find Package.appxmanifest at $manifestPath -- run this script from its location inside the repo's scripts\ folder."
    exit 1
}

[xml]$manifest = Get-Content -Path $manifestPath
$identityName = $manifest.Package.Identity.Name

if ([string]::IsNullOrWhiteSpace($identityName)) {
    Write-Error "Could not read Identity/@Name from $manifestPath."
    exit 1
}

Write-Host "Looking for an installed package with Identity Name '$identityName'..."
$packages = Get-AppxPackage -Name $identityName

if (-not $packages) {
    Write-Host "SecretCsv doesn't appear to be installed or registered (no AppX package found for '$identityName') -- nothing to reset."
    exit 0
}

$anyFilesFound = $false

foreach ($package in $packages) {
    $localState = Join-Path $env:LOCALAPPDATA "Packages\$($package.PackageFamilyName)\LocalState"

    if (-not (Test-Path $localState)) {
        Write-Host "No AppData folder found at $localState -- nothing to reset for package family '$($package.PackageFamilyName)'."
        continue
    }

    $files = @(Get-ChildItem -Path $localState -Filter '*.md' -File) + @(Get-ChildItem -Path $localState -Filter '*.txt' -File)

    if ($files.Count -eq 0) {
        Write-Host "AppData is already empty at $localState -- nothing to reset for package family '$($package.PackageFamilyName)'."
        continue
    }

    $anyFilesFound = $true
    Write-Host "Found $($files.Count) file(s) in $localState :"
    $files | ForEach-Object { Write-Host "  $($_.Name)" }

    if ($Force -or $PSCmdlet.ShouldProcess($localState, "Delete $($files.Count) file(s)")) {
        $files | Remove-Item -Force
        Write-Host "Done. SecretCsv will start fresh (empty AppData -- no auto-seeding, README.md section 6) on next launch."
    }
}

if (-not $anyFilesFound) {
    Write-Host "Nothing needed resetting."
}
