// Copyright (c) 2026 edwest19
// Generated by Claude.
//
// ============================================================================
// PORT NOTE (Claude, Sonnet 5, 2026-08-18):
// Ported verbatim from SecretLead's Models\CsvTable.cs as part of the
// SecretLead -> SecretCsv port (see README.md, chat history). Only the
// namespace changed (SecretLead.Models -> SecretCsv.Models); the logic below
// is byte-for-byte identical to SecretLead's working, reviewed version.
// ============================================================================

namespace SecretCsv.Models;

/// <summary>
/// A parsed CSV file: the header row, plus each data row as a
/// case-insensitive column-name → value lookup (matching how tag names are
/// matched against CSV headers everywhere else — README.md §4).
/// </summary>
public sealed class CsvTable
{
    public required IReadOnlyList<string> Headers { get; init; }

    public required IReadOnlyList<IReadOnlyDictionary<string, string>> Rows { get; init; }
}
