// Copyright (c) 2026 edwest19
// Generated by Claude.
//
// ============================================================================
// PORT NOTE (Claude, Sonnet 5, 2026-08-18):
// Ported verbatim from SecretLead's Models\TagFileDefinition.cs as part of
// the SecretLead -> SecretCsv port (see README.md, chat history). Only the
// namespace changed (SecretLead.Models -> SecretCsv.Models); the logic below
// is byte-for-byte identical to SecretLead's working, reviewed version.
// The <see cref="Services.TagFileParser"/> reference below is forward-looking
// -- that service hasn't been ported yet (it's Step 2), so this doc comment
// will show an unresolved cref until then. That's expected, not a bug.
// ============================================================================

namespace SecretCsv.Models;

/// <summary>
/// A parsed tag file (README.md §4): an entity name plus an ordered list of
/// tag names. Deliberately not a "schema" in the type/constraint sense —
/// just a name-matcher and two positional roles.
/// </summary>
public sealed class TagFileDefinition
{
    /// <summary>
    /// The entity name from the tag file's <c>##</c> line. Also the
    /// filename stem for this entity's AppData store (README.md §5):
    /// <c>&lt;EntityName&gt;.md</c> / <c>&lt;EntityName&gt;.txt</c>.
    /// </summary>
    public required string EntityName { get; init; }

    /// <summary>
    /// Every <c>### TAG</c> name, in the order declared in the tag file.
    /// Must contain at least 2 entries — enforced by <see cref="Services.TagFileParser"/>.
    /// </summary>
    public required IReadOnlyList<string> Tags { get; init; }

    /// <summary>
    /// The first declared tag — top-level grouping, and the field that
    /// explodes into multiple records on a semicolon-delimited value at
    /// import time (README.md §4).
    /// </summary>
    public string CategoryTag => Tags[0];

    /// <summary>
    /// The second declared tag — the searchable identifying field used for
    /// browsing (README.md §4).
    /// </summary>
    public string NicknameTag => Tags[1];
}
